 name: Docker Build
 on:
    push:
        branches:
          - main
 jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        
        - name: Build Docker image
          run: docker build -t devops-lab:test .

        - name: Run container
          run: |
            docker run -d --name test-container -p 8080:8000 devops-lab:test
            sleep 5

        - name: Check container is running
          run: |
                if [ "$(docker inspect -f '{{.State.Running}}' test-container)" != "true" ]; then
                echo "❌ Контейнер упал"
                docker logs test-container
                exit 1
                fi
                echo "✅ Контейнер работает"

        - name: Health check
          run: |
              for i in {1..10}; do
              if curl -sf http://localhost:8080/ > /dev/null; then
              echo "✅ Приложение отвечает"
              exit 0
              fi
              sleep 2
              done
              echo "❌ Приложение не ответило"
              docker logs test-container
              exit 1

        - name: Cleanup
          if: always()
          run: docker rm -f test-container || true

